### ISSUE TITLE
Missing key for one of the secrets in main container's manifest

### ISSUE THREAD

**Issue by jkozlowicz** [GoogleCloudPlatform/gmemegen#16]
1. Go to: https://codelabs.developers.google.com/codelabs/cloud-postgresql-gke-memegen/#7
2. Go to section: Main Container
3. The following snippet seems to be missing the `password` key:

```       
      - name: gmemegen
          image: gcr.io/[PROJECT_ID]/gmemegen
          ports:
            - containerPort: 8080
          # Set env variables used for Postgres Connection
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                                             <--- shouldn't there be [key: password] here?
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: dbname
```
